apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ygjbdo5u1-java-quarkus
  janus-idp.io/tekton: ygjbdo5u1-java-quarkus
  backstage.io/kubernetes-id: ygjbdo5u1-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ygjbdo5u1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
